services:
  - type: web
    name: chat-insider
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
